SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDER_PAYMENTS;

-- Q1. Find the total revenue generated by the platform.
SELECT
	SUM(PRICE) AS REVENUE
FROM
	ORDER_ITEMS;

--Q2. Calculate revenue per month based on order purchase timestamp.
SELECT
	TO_CHAR(O.ORDER_PURCHASE_TIMESTAMP, 'YYYY-MM') AS MONTH_OF_ORDER,
	SUM(OI.PRICE) AS REVENUE
FROM
	ORDERS O
	JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY
	MONTH_OF_ORDER
ORDER BY
	MONTH_OF_ORDER;

--Q3. Find the average value per order.
SELECT
	ROUND(SUM(PRICE) / COUNT(DISTINCT ORDER_ID), 2) AS AOV_REVENUE
FROM
	ORDER_ITEMS;

--Q4. Find products with highest number of items sold.
SELECT
	PRODUCT_ID,
	COUNT(*) AS ITEM_SOLD
FROM
	ORDER_ITEMS
GROUP BY
	PRODUCT_ID
ORDER BY
	ITEM_SOLD DESC
LIMIT
	10;

--Q5. Find products generating the highest total revenue.
SELECT
	PRODUCT_ID,
	SUM(PRICE) AS REVENUE
FROM
	ORDER_ITEMS
GROUP BY
	PRODUCT_ID
ORDER BY
	REVENUE DESC
LIMIT
	10;

--Q6. Find most used payment types.
SELECT
	PAYMENT_TYPE,
	COUNT(*) AS COUNT_OF_PAYMENT
FROM
	ORDER_PAYMENTS
GROUP BY
	PAYMENT_TYPE
ORDER BY
	COUNT_OF_PAYMENT DESC;

--Q7. Analyze installment usage for credit card payments.
SELECT
	PAYMENT_INSTALLMENTS,
	COUNT(*) AS PAYMENT_USAGE
FROM
	ORDER_PAYMENTS
WHERE
	PAYMENT_TYPE = 'credit_card'
GROUP BY
	PAYMENT_INSTALLMENTS
ORDER BY
	PAYMENT_USAGE DESC;

--Q8. Identify top 10 customers by total spending.
SELECT
	O.CUSTOMER_ID,
	SUM(OP.PAYMENT_VALUE) AS TOTAL_SPENDING
FROM
	ORDERS O
	JOIN ORDER_PAYMENTS OP ON O.ORDER_ID = OP.ORDER_ID
GROUP BY
	O.CUSTOMER_ID
ORDER BY
	TOTAL_SPENDING DESC
LIMIT
	10;

--Q9. Find how many customers: ordered once, ordered multiple times
SELECT 
  CASE 
    WHEN order_count = 1 THEN 'one_time' 
    ELSE 'repeat' 
  END AS customer_type,
  COUNT(*) AS customer_count
FROM (
  SELECT c.customer_unique_id, COUNT(o.order_id) AS order_count
  FROM orders o
  JOIN customers c ON o.customer_id = c.customer_id
  GROUP BY c.customer_unique_id
) AS customer_orders
GROUP BY customer_type;

--Q10. Find which states have the highest number of orders.
SELECT
	C.CUSTOMER_STATE,
	COUNT(*) AS TOTAL_ORDERS
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_STATE
ORDER BY
	TOTAL_ORDERS DESC;
	
--Q11. Calculate average number of products per order.
SELECT
	AVG(PRODUCT_COUNT) AS AVG_PRODUCTS
FROM
	(
		SELECT
			ORDER_ID,
			COUNT(PRODUCT_ID) AS PRODUCT_COUNT
		FROM
			ORDER_ITEMS
		GROUP BY
			ORDER_ID
	) AS ORDER_COUNTS;

--Q12. Find top 10 highest value orders.
SELECT
	ORDER_ID,
	SUM(PAYMENT_VALUE) AS PAYMENT_VALUE
FROM
	ORDER_PAYMENTS
GROUP BY
	ORDER_ID
ORDER BY
	PAYMENT_VALUE DESC
LIMIT
	10;

